"""Verified official/issuer offer-document fallbacks.

This registry is data only. Every entry is still subject to the runtime runner's
exact-host, PDF-magic, issuer-identity and fill-only merge gates before use.
"""

VALIDATED_OFFER_DOCUMENTS: dict[str, dict[str, str]] = {
    "om-galaxy-limited": {
        "company": "OM Galaxy Limited",
        "url": "https://omgalaxymould.com/wp-content/uploads/2026/09/Project-Om_-RHP_with_RFS.pdf",
        "host": "omgalaxymould.com",
        "type": "RHP",
        "title": "Red Herring Prospectus",
        "sourcePage": "https://omgalaxymould.com/",
    },
    "injecto-polymers-limited": {
        "company": "Injecto Polymers Limited",
        "url": "https://ipostatus.integratedregistry.in/PDFFILES/INJECTORHP.pdf",
        "host": "ipostatus.integratedregistry.in",
        "type": "RHP",
        "title": "Red Herring Prospectus",
        "sourcePage": "https://ipostatus.integratedregistry.in/RegistrarsToSTANew.aspx",
        "extractionSource": "Registrar website",
        "documentSource": "Integrated Registry",
        "sourceName": "Integrated Registry offer document",
        "sourceKind": "registrar-filing",
    },
    "manika": {
        "company": "Manika Plastech Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/sep-2026/1788774340354.pdf",
        "host": "www.sebi.gov.in",
        "type": "RHP",
        "title": "Red Herring Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/sep-2026/manika-plastech-limited-rhp_104296.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI Red Herring Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "shakti-polytarp-limited": {
        "company": "Shakti Polytarp Limited",
        "url": "https://shaktipolytarp.com/wp-content/uploads/2025/10/DRHP_Shakti_29092025.pdf",
        "host": "shaktipolytarp.com",
        "type": "DRHP",
        "title": "Draft Red Herring Prospectus",
        "sourcePage": "https://shaktipolytarp.com/ipo-drhp-and-industry-report/",
    },
    "vama-wovenfab-limited": {
        "company": "Vama Wovenfab Limited",
        "url": "https://vamawoven.com/wp-content/uploads/2026/09/RHP_VamaWovenfabLimited-2.pdf",
        "host": "vamawoven.com",
        "type": "RHP",
        "title": "Red Herring Prospectus",
        "sourcePage": "https://vamawoven.com/rhp/",
    },
    "sunshine": {
        "company": "Sunshine Pictures Limited",
        "url": "https://www.bseindia.com/downloads/ipo/361148/ipo_T3/Prospectus_20260821184134.pdf",
        "host": "www.bseindia.com",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.bseindia.com/downloads/ipo/361148/ipo_T3/Prospectus_20260821184134.pdf",
        "extractionSource": "BSE",
        "documentSource": "BSE",
        "sourceName": "BSE final Prospectus",
        "sourceKind": "exchange-filing",
    },
    "symbiotec": {
        "company": "Symbiotec Pharmalab Limited",
        "url": "https://nsearchives.nseindia.com/corporate/FP_INE899I01028_31AUG2026.pdf",
        "host": "nsearchives.nseindia.com",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://nsearchives.nseindia.com/corporate/FP_INE899I01028_31AUG2026.pdf",
        "extractionSource": "NSE",
        "documentSource": "NSE",
        "sourceName": "NSE final Prospectus",
        "sourceKind": "exchange-filing",
    },
    "pranav": {
        "company": "Pranav Constructions Limited",
        "url": "https://www.bseindia.com/downloads/ipo/335516/IPO%20Open/6RHPSigned_20260903150028.pdf",
        "host": "www.bseindia.com",
        "type": "RHP",
        "title": "Red Herring Prospectus",
        "sourcePage": "https://www.bseindia.com/downloads/ipo/335516/IPO%20Open/6RHPSigned_20260903150028.pdf",
        "extractionSource": "BSE",
        "documentSource": "BSE",
        "sourceName": "BSE Red Herring Prospectus",
        "sourceKind": "exchange-filing",
    },
    "augmont": {
        "company": "Augmont Enterprises Limited",
        "url": "https://nsearchives.nseindia.com/corporate/FP_INE16W401027_27AUG2026.pdf",
        "host": "nsearchives.nseindia.com",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://nsearchives.nseindia.com/corporate/FP_INE16W401027_27AUG2026.pdf",
        "extractionSource": "NSE",
        "documentSource": "NSE",
        "sourceName": "NSE final Prospectus",
        "sourceKind": "exchange-filing",
    },
    "tempsens": {
        "company": "Tempsens Instruments (India) Limited",
        "url": "https://nsearchives.nseindia.com/corporate/FP_INE1KZI01025_25AUG2026.pdf",
        "host": "nsearchives.nseindia.com",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://nsearchives.nseindia.com/corporate/FP_INE1KZI01025_25AUG2026.pdf",
        "extractionSource": "NSE",
        "documentSource": "NSE",
        "sourceName": "NSE final Prospectus",
        "sourceKind": "exchange-filing",
    },
    "leap": {
        "company": "Leap India Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/aug-2026/1786535192735.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/aug-2026/leap-india-limited-prospectus_103511.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "propshop": {
        "company": "Propshop Events and Exhibitions Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/jul-2026/1785404948142.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/jul-2026/propshop-events-and-exhibitions-limited-prospectus_103111.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "alpinetex": {
        "company": "Alpine Texworld Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/aug-2026/1786621533716.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/aug-2026/alpine-texworld-limited-prospectus_103604.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "aastha": {
        "company": "Aastha Spintex Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/jul-2026/1785320834804.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/jul-2026/aastha-spintex-limited-prospectus_103092.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "rambhajo": {
        "company": "Advit Jewels Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/jun-2026/1782728190936.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/jun-2026/advit-jewels-limited-prospectus_102425.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "csm": {
        "company": "CSM Technologies Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/jul-2026/1782884582544.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/jun-2026/csm-technologies-limited-prospectus_102473.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "cleanmax": {
        "company": "Clean Max Enviro Energy Solutions Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/feb-2026/1772097780247.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/feb-2026/clean-max-enviro-energy-solutions-limited-prospectus_99987.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "gspcrop": {
        "company": "GSP Crop Science Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/apr-2026/1776851251292.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/mar-2026/gsp-crop-science-limited-prospectus_101040.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "hexagon": {
        "company": "Hexagon Nutrition Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/jun-2026/1781074175044.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/jun-2026/hexagon-nutrition-limited-prospectus_101991.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "cmpdi": {
        "company": "Central Mine Planning & Design Institute Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/apr-2026/1775128471900.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/apr-2026/central-mine-planning-and-design-institute-limited-prospectus_100707.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "innovision": {
        "company": "Innovision Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/mar-2026/1774008043195.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/mar-2026/innovision-limited-prospectus_100489.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "jnpr": {
        "company": "Juniper Green Energy Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/aug-2026/1787054356074.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/aug-2026/juniper-green-energy-limited-prospectus_103747.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "aye": {
        "company": "Aye Finance Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/feb-2026/1770879625663.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/feb-2026/aye-finance-limited-prospectus_99708.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "cmll": {
        "company": "Caliber Mining and Logistics Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/jul-2026/1784698849378.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/jul-2026/caliber-mining-and-logistics-limited-prospectus_102990.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "lcl": {
        "company": "Lohia Corp Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/jul-2026/1785231911524.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/jul-2026/lohia-corp-limited-prospectus_103075.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "mvelectro": {
        "company": "MV Electrosystems Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/aug-2026/1785823205427.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/aug-2026/mv-electrosystems-limited-prospectus_103331.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "manipalhos": {
        "company": "Manipal Health Enterprises Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/aug-2026/1785732646843.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/aug-2026/manipal-health-enterprises-limited-prospectus_103300.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "ompower": {
        "company": "Om Power Transmission Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/apr-2026/1776237369286.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/apr-2026/om-power-transmission-limited-prospectus_100928.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "kissht": {
        "company": "Onemi Technology Solutions Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/jun-2026/1781763357383.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/may-2026/onemi-technology-solutions-limited-prospectus_102192.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "kusumgar": {
        "company": "Kusumgar Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/jul-2026/1784001026291.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/jul-2026/kusumgar-limited-prospectus_102792.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "knack": {
        "company": "Knack Packaging Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/jul-2026/1783319397647.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/jul-2026/knack-packaging-limited-prospectus_102599.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "pngsreva": {
        "company": "PNGS Reva Diamond Jewellery Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/mar-2026/1772433551022.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/feb-2026/pngs-reva-diamond-jewellery-limited_100068.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "indomim": {
        "company": "INDO-MIM Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/jul-2026/1784523106091.pdf",
        "host": "www.sebi.gov.in",
        "type": "RHP",
        "title": "Red Herring Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/jul-2026/indo-mim-limited-rhp_102938.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI Red Herring Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "omni": {
        "company": "Omnitech Engineering Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/feb-2026/1771933506852.pdf",
        "host": "www.sebi.gov.in",
        "type": "RHP",
        "title": "Red Herring Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/feb-2026/omnitech-engineering-limited-rhp_99941.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI Red Herring Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "rsl": {
        "company": "Rajputana Stainless Limited",
        "url": "https://www.sebi.gov.in/sebi_data/attachdocs/apr-2026/1775629467259.pdf",
        "host": "www.sebi.gov.in",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://www.sebi.gov.in/filings/public-issues/apr-2026/rajputana-stainless-limited-prospectus_100791.html",
        "extractionSource": "SEBI",
        "documentSource": "SEBI",
        "sourceName": "SEBI final Prospectus",
        "sourceKind": "regulatory-filing",
    },
    "ardee": {
        "company": "Ardee Industries Limited",
        "url": "https://nsearchives.nseindia.com/corporate/FP_INE0XNF01022_10AUG2026.pdf",
        "host": "nsearchives.nseindia.com",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://nsearchives.nseindia.com/corporate/FP_INE0XNF01022_10AUG2026.pdf",
        "extractionSource": "NSE",
        "documentSource": "NSE",
        "sourceName": "NSE final Prospectus",
        "sourceKind": "exchange-filing",
    },
    "powerica": {
        "company": "Powerica Limited",
        "url": "https://nsearchives.nseindia.com/corporate/FP_INE921L01032_30MAR2026.pdf",
        "host": "nsearchives.nseindia.com",
        "type": "Prospectus",
        "title": "Prospectus",
        "sourcePage": "https://nsearchives.nseindia.com/corporate/FP_INE921L01032_30MAR2026.pdf",
        "extractionSource": "NSE",
        "documentSource": "NSE",
        "sourceName": "NSE final Prospectus",
        "sourceKind": "exchange-filing",
    },
}
