import assert from "node:assert/strict";
import fs from "node:fs";
const html=fs.readFileSync("drhp.html","utf8"),app=fs.readFileSync("assets/drhp.js","utf8"),index=fs.readFileSync("index.html","utf8");
const sebi=JSON.parse(fs.readFileSync("data/drhp-filings.json","utf8")),nse=JSON.parse(fs.readFileSync("data/nse-drhp-filings.json","utf8"));
assert.match(index,/href="drhp\.html"[^>]*>DRHP \/ Pre-IPO<\/a>/);assert.match(html,/id="drhpSearch"/);
assert.match(html,/DRHP Filed \/ Pre-IPO/);assert.match(html,/not yet categorized as Upcoming, Open, Closed, or Listed/);assert.match(html,/Official SEBI \+ NSE sources/);
assert.match(app,/fetch\("data\/drhp-filings\.json"/);assert.match(app,/fetch\("data\/nse-drhp-filings\.json"/);assert.match(app,/fetch\("data\/ipos\.json"/);
assert.match(app,/mergeOfficialDraftSources/);assert.match(app,/buildPreIpoView/);assert.match(app,/View official filing/);
assert.equal(sebi.coverage.filing_records,sebi.companies.reduce((n,c)=>n+c.filings.length,0));assert.equal(sebi.coverage.year,2026);assert.ok(sebi.coverage.pages_fetched>=2);
assert.equal(nse.coverage.filing_records,nse.companies.reduce((n,c)=>n+c.filings.length,0));assert.equal(nse.coverage.year,2026);assert.ok(nse.companies.some(c=>/\babakkus\b/i.test(c.issuer_name)));
for(const c of sebi.companies)assert.match(c.latest_filing_url,/^https:\/\/www\.sebi\.gov\.in\/filings\/public-issues\//);
for(const c of nse.companies)assert.match(c.latest_filing_url,/^https:\/\/nsearchives\.nseindia\.com\/corporate\//);
console.log(JSON.stringify({drhp_ui_tests:{sebi_companies:sebi.companies.length,nse_companies:nse.companies.length,dual_source:true,lifecycle_copy:true}}));
